
---

### ⚙️ `mkdocs.yml`

site_name: Xolo Pipeline
site_description: A lightweight open-source pipeline for solo creators and small studios.
site_url: https://xolo.ronnyascencio.com
use_directory_urls: false
repo_url: https://github.com/ronnyascencio/xolo-pipeline
repo_name: ronnyascencio/xolo-pipeline

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: black
      accent: indigo
  icon:
    repo: fontawesome/brands/github

  extra:
    social:
#      - icon: fontawesome/brands/twitter
#        link: https://twitter.com/tu_usuario
      - icon: fontawesome/brands/linkedin
        link: https://linkedin.com/in/ronnyascencio

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Commands: commands.md



plugins:
  - search
  - mkdocstrings:
      handlers:
        python: {}


