name: Bug Report
description: Report an issue or unexpected behavior
title: "[Bug] <title>"
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following form to help us reproduce and fix the issue.
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: Describe the bug in detail.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run `xolo init`
        2. Select...
        3. See error...
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: Windows 11, macOS Ventura, Ubuntu 24.04, etc.
  - type: input
    id: python
    attributes:
      label: Python Version
      placeholder: e.g., 3.11
  - type: input
    id: uv
    attributes:
      label: uv version
      placeholder: e.g., uv 0.1.19
