name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature] <title>"
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Tell us how this feature could help your workflow or others.
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      placeholder: I’d like to be able to...
    validations:
      required: true
  - type: textarea
    id: motivation
    attributes:
      label: Why is this feature important?
      placeholder: It would help because...
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: I’ve tried using...
